set-option -g history-limit 25000
set -g mouse on

# Prefix key change: Ctrl-b to Ctrl-a
unbind C-b
unbind C-a
set -g prefix C-a
bind C-a send-prefix

# for neovim
set -sg escape-time 10
set-option -g focus-events on

# vi for copy mode
setw -g mode-keys vi

# status bar
set -g status-right " "
set -g status-style "fg=#665c54"
set -g status-left-style "fg=#928374"

set -g status-bg default
set -g status-position top
set -g status-interval 1
set -g status-left ""


# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @tpm_plugins '          \
  tmux-plugins/tpm             \
  tmux-plugins/tmux-sensible   \
  tmux-plugins/tmux-resurrect  \
  tmux-plugins/tmux-yank       \
'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# reload configuration
bind-key -r r source-file ~/.config/tmux/.tmux.conf \; display-message "Config reloaded successfully!"

# term colors, these are the correct ones according to neovim checkhealth

set-option -g default-terminal "screen-256color"
