#!/bin/bash

DOTFILES_DIR="$HOME/Repos/github.com/xssns/dotfiles"
XDG_CONFIG_HOME="$HOME/.config"

create_directories() {
  local directories=("$@")
  for dir in "${directories[@]}"; do
    mkdir -p "$dir"
  done
}

create_symlinks() {
  local items=("$@")
  for item in "${items[@]}"; do
    IFS=':' read -r source target <<<"$item"
    if [ -L "$target" ]; then
      echo "Removing existing symlink $target"
      unlink "$target"
    elif [ -d "$target" ]; then
      echo "Warning: $target is a directory. Skipping..."
      continue
    elif [ -e "$target" ]; then
      echo "Warning: $target already exists. Skipping..."
      continue
    fi
    ln -s "$DOTFILES_DIR/$source" "$target"
    echo "Created symlink for $source"
  done
}

common_directories=(
  "$XDG_CONFIG_HOME/alacritty"
  "$XDG_CONFIG_HOME/alacritty/themes"
  "$XDG_CONFIG_HOME/skhd"
  "$XDG_CONFIG_HOME/k9s"
  "$XDG_CONFIG_HOME/qutebrowser"
  "$XDG_CONFIG_HOME/sway"
)

common_items=(
  "alacritty.toml:$XDG_CONFIG_HOME/alacritty/alacritty.toml"
  "k9s/skin.yml:$XDG_CONFIG_HOME/k9s/skin.yml"
  ".inputrc:$HOME/.inputrc"
  ".tmux.conf:$HOME/.tmux.conf"
  "nvim:$XDG_CONFIG_HOME/nvim"
  "skhdrc:$XDG_CONFIG_HOME/skhd/skhdrc"
  ".zprofile:$HOME/.zprofile"
  ".zshrc:$HOME/.zshrc"
  "qutebrowser/config.py:$XDG_CONFIG_HOME/qutebrowser/config.py"
  "sway/config:$XDG_CONFIG_HOME/sway/config"
)

create_directories "${common_directories[@]}"
create_symlinks "${common_items[@]}"

# MacOS specific setup
if [[ "$OSTYPE" == darwin* ]]; then
  macos_directories=(
    "$HOME/.qutebrowser"
  )
  macos_items=(
    "qutebrowser/config.py:$HOME/.qutebrowser/config.py"
  )
  create_directories "${macos_directories[@]}"
  create_symlinks "${macos_items[@]}"
fi

# and when called it needs to be quoted.
export ZETTELKASTEN="/Users/ssns/Zettelkasten/second-brain/"
# export ZETTELKASTEN=("/Users/ssns/Zettelkasten")
# ln -sf "$ZETTELKASTEN" ~/Zettelkasten

# Packages

# install brew
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# brew install --cask font-iosevka-nerd-font
# brew install --cask font-ubuntu-mono-nerd-font

# brew packages Mac
# brew install --cask alacritty
# amethyst fzf nvim bash-completion@2 kubectl starship

# set up prompt
# mkdir -p "$HOME/.zsh"
# git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"
